runtime: go126
instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 1

env_variables:
  GEMINI_LOCATION: global
  GEMINI_STICKER_MODEL: gemini-3.5-flash-lite
  LINE_CHANNEL_SECRET_NAME: linebot-channel-secret
  LINE_CHANNEL_TOKEN_NAME: linebot-channel-token
